spring:
  application:
    name: UberBookingService
  datasource:
    url: jdbc:mysql://localhost:3306/Uber_RideUp
    username: root
    password: As22@$%100
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    # show-sql:
  flyway:
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 1114

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka
  instance:
    preferIpAddress: true